### ISSUE TITLE
[BUG]: regular expressions in ignore mode bug

### ISSUE THREAD

**Issue by Falcion** [Falcion/UNITADE#30]
### What the essence of the bug

```Uncaught (in promise) SyntaxError: Invalid regular expression: /*logs/: Nothing to repeat (at VM212 plugin:unitade:590:17)
    at new RegExp (<anonymous>)
    at _UNITADE_PLUGIN.eval (VM212 plugin:unitade:590:17)
    at Generator.next (<anonymous>)
    at eval (VM212 plugin:unitade:73:61)
    at new Promise (<anonymous>)
    at __async (VM212 plugin:unitade:57:10)
    at eval (VM212 plugin:unitade:586:45)
    at e.tryTrigger (app.js:1:726617)
    at e.trigger (app.js:1:726550)
    at t.trigger (app.js:1:744681)
```
    
Is thrown, for this exception, just use the ignore masks module of this plugin.

Solution:

```ts
//L#35 of main.ts

if (this.settings.is_ignore) {
                for (const mask of this.settings.ignore_masks.split(';')) {
                    const escapedMask = mask.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // Escape special characters
                    console.log('Escaped Mask:', escapedMask); // Log the escaped mask
                    try {
                        const regex = new RegExp(escapedMask);
                        if (regex.test(file.name)) {
                            return;
                        }
                    } catch (error) {
                        console.error('Error creating regular expression:', error);
                    }
                }
            }
```

### Version of an project's essence

2.0.0

### On what OS you have encountered the bug.

Windows

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
Fixed in last release (v2.1.0).
